### ISSUE TITLE
Check different SES

### ISSUE THREAD

**Issue by matthieudolci** [AlexRRR/check_sesquota#1]
Hello,

First of all thanks for this really useful plugin.

We are using it to check our quota on N. Virginia and we would like to check our quota for Ireland and Oregon, but we have not been able to figure out how to do so.

Could you help us out?

Thanks

**Comment by AlexRRR** [comment]
Its been three years already? wow. @matthieudolci sure thing. Last time I was working SES was only available in one region so this was not implemented. It seems the Boto API also changed a bit. You should be able now to test with:

```
python check_sesquota.py -c 10 -w 20  -r eu-west-1
```

Please note that the default region is _us-east-1_.

**Comment by matthieudolci** [comment]
Thanks @AlexRRR this is just perfect!!!
